/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:8d0174ae-b08c-46a5-a6fe-e175a60abc68",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_I8MeV1itM",
    "aws_user_pools_web_client_id": "1p1fgahpl9suu7nrbq6kqlumcu",
    "oauth": {}
};


export default awsmobile;
